# frozen_string_literal: true

source "https://rubygems.org"

group :test do
  gem "rspec"
  gem "rack-test"
end

group :development do
  gem "ruby-lsp", require: false
  gem "io-watch"
  gem "dotenv"
end

gem "roda"
gem "falcon"
gem "async"
gem "async-http", "~> 0.94.2"

