# frozen_string_literal: true

source "https://rubygems.org"

group :test do
  gem "rspec"
  gem "rack-test"
end

group :development do
  gem "ruby-lsp", require: false
  gem "io-watch"
  gem "dotenv"
end

gem "roda"
gem "falcon"
gem "async"
gem "async-http", "~> 0.94.2"
gem "redis", "~> 5.4"
gem "rack", "~> 3.2"
gem "dry-struct", "~> 1.8"
gem "dry-types", "~> 1.9"
gem "dry-schema", "~> 1.16"
