# frozen_string_literal: true

source "https://rubygems.org"

gem "roda"
gem "falcon"
gem "async"

group :test do
  gem "rspec"
  gem "rack-test"
end

group :development do
  gem "ruby-lsp", require: false
end
