name: Continuous Integration (DEV)

on:
  workflow_dispatch:
  push: {}
  pull_request: {}

jobs:
  rspec-tests:
    name: Ruby Roda Tests
    runs-on: ubuntu-latest
    env:
      REDIS_URL: redis://localhost:6379
    services:
      redis:
        image: redis:7-alpine
        ports:
          - "6379:6379"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        working-directory: server
        run: bundle exec rspec
